os:
- linux
services:
- docker
language: node_js
jdk:
- openjdk8
sudo: false
cache:
  directories:
  - node
  - node_modules
  - "$HOME/.m2"
  - "$HOME/.yarn-cache"
  - "$HOME/.sonar/cache"
addons:
  sonarcloud:
    organization: "securityrat"
    token:
      secure: iEsQimM9dEZJKOYRIhQxT3Y+bQ2LCGVUm0qtl6J1ki/eUO3RNArGFxVPEYXM0pX86fA5/FNlUY7Efy7WLSwW6nLMeMW4pd0s2Z7xx5xDOkgiuIXfx8klE/YW8AQHggl/qcYm0M2VyFUVnRzkGfIYgNxKykA0MKNFQ2pgXeMh3MmVAqZ9a3MGd6hVU7p+fr1qDpN0Wwss3dj35pO2k0Cskyq89klN1Gd9qfZvpYoelXdP7fTj87KrbQx5K976RxGSok77szcBNegS3pKblQFWPcV9iqwnNkZHoeDsbEa4TsOi/5CBb/lMhj+oc53KAoe9SMAC5irHTQBf2Huvvl5WfZbtqD17YqQ7jbsErG3GBDc5SsATwKhv2AiZIjKYfe9AfQICf2S87sFP2CyzYow1mf5Pm0DI8b6oN7aOLzSTvqQmd3/MVhB1BBGFuLz34/q+J2KAnOkfleQa6f2Onp7XK86xFStjJUSbParXg3xMPciEsvQxNwqGqnHB3ooVkKfOBccHRYHJKHyWfaYgd/KDIo9sqhIQz/XRb+RZJvSqNt8ahGXdtmg6GuWAm2N3Ic9GVSJu3PxzywYYBFfSp6vRg1zQ+DYM0io+JLuBHd4M0MgxcZ1scUPHQe+VrPnlANSI/gnWBBvCoSwEqggUIC/x3w0R7U0er+C/a8LVxXmb4aA=
    branches:
    - master
    - dev
env:
  global:
  - REPOS_SCRIPTS=$TRAVIS_BUILD_DIR/travis/scripts
  - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
  - SPRING_JPA_SHOW_SQL=false
  - DOCKER_REPO=securityrat/case-management
  - secure: H1q/AM/ljDpTk3Z7l2/WPVFV4JeraiAqa7LvVV3GudGXN8B1CS8Bj3+TnQcmyFmXu1cWD5Hq2EfRIZqttTlpge28Id0Ad+iL6j1Sm/xBJy9ltFdP5xjsWuF+06YH/lAXwmaOGHoC4wHQ6sbI0wbUQ775ABIoz2/talLF4podxvAJOuZIMJjX4akDaAx+uac5Th8QFNlRpMgdST2aUUSocFavJBxsX4jjxT6XIiUuvtVZqJ3kt/+YUju1Saez/jLO9nL0uHwNiu8J2V2keEj0B/9hc2ZzEUXwZpKPtEMkOpDob4aDsb7ljClsqOURSkulmbRQ5KYqYEIfjLFuYXXfpbq7SnN1/5Qd1nlloMMBqiVTad1/w97j7m15XECZ+hctJO40XxJ4ec+34HfSi+Gm0zEHtg4hC/S05LRIPH+ky4MyzIluxm0DcLFKP9ajc8+vIZ2XZpJcfx6fhWP+iQJP6aKVtclmuPww8Ru/L18/2JhslDOVGTdxY/Lkuf7PBSlTKIDXKTepPyShCOFf4cZmYI+R9QlVSWyn221VRS7OQ6Ty6Bxmn4UwQc/aXYOXLD3rHuNR3CvpiJA/7AwbdcI18zN/zGRX5fGZPMzjIoUuuUMUNg0Rkw2N6jrYOWWUpkKhXavTAAfhkHm+HZTEWS1Ch/U2/R09MQ7RqQoLdSG151Y=
  - secure: O1iKPJcS8SvHNjsC1KfASw42f1KPDVoa9ePheO/+UB20Mg2mnooIrZO+2ksTATGSTjG2pVHR2c7hM3WEkdPrt7MzV+g0pGw/THuyZU90p3JkccBFudR+d9z7MZnwXzdrV6EKmEalPmB/HlBxXugUj5hl0S9kvS31J1DNWthzZ6ZE2uvQPKSMW/Fp+5kg5cj0XVUIgPUgmUnTgUjvLF1nSdd2PNEJ3Bf2p6SQQQVx0KInR3+iZGS/h5SX5CWRuF02IARt0IemKGflkpihMw1mtAGH//CRnV02bzrplwfaioIhQqV4C2mwlGfF+irMOmZ2yAyyuEWdj2/35V7re8oDcdQtwrpY+Y7moDjFgS4iEQIqrOQgQpJAoyjuzKjgJ5QIPAhkzU8JMeqMnK5wfW6S4O/mA0QR5fVJMdQok6GjLmZWtRxzJQW4v+jcJ3pQBsyJCmMMVHDHwyVP4Ss71MqpI7nFTCNN+wFTMcsx1xr9E++rq+xcwdQvwQn5/Bp+DzgBezv2HQhrxKS8ozWpGMeUiDalR3N0WGZEmgtFoOy5nQ3PePPTb4JFqaOY+wD6MKsfvBUxnysmpEmpU93pVzUjFPvUmZPcE2JuFNB7KCKMjsCmGThPT7fnMuCWbuDPYeL0jCzn/LYtg+szamCz7KdXtTS0alCN0ZUKO4i+kzqGipU=
before_install:
- sudo /etc/init.d/mysql stop
- sudo /etc/init.d/postgresql stop
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
install:
- yarn install
script:
- chmod +x mvnw
- "./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent test sonar:sonar"
before_deploy:
- "./mvnw verify -Pprod -DskipTests -Ddocker.repository=$DOCKER_REPO"
deploy:
  provider: script
  script: bash $REPOS_SCRIPTS/docker_push
  on:
    branch: master
    condition: "-n $TAG_NAME"
notifications:
  email:
    on_success: change
    on_failure: always
    on_start: false
