@startuml

actor user
participant gateway
participant caseManagement
database caseManagementDB
participant Jira

note over gateway
    All Requests are proxied
    via this component
end note

user -> caseManagement: Export artifact requirement
caseManagement -> caseManagementDB: Get access token
caseManagementDB -> caseManagement: accessToken Object

alt ticket system instance not in DB
    caseManagement -> user: 400 Invalid Ticket System URL
end

alt Access token exist in DB
    caseManagement -> Jira: Check validity of access token
    Jira -> caseManagement: Response
end

alt Access token doesn't exist in DB or token invalid
    caseManagement -> Jira: Get request token
    Jira -> caseManagement: Temporary authorization url
    caseManagement -> user: Temporary Jira authorization URL with redirect URL to case management
    user -> user: Open temporary JIRA authorization URL in new Tab to give authorization
    user -> Jira: User authorizes token
    Jira -> caseManagement: Redirect with access code
    caseManagement -> Jira: Get access token with access code
    Jira -> caseManagement: Access token
    caseManagement -> caseManagement: Encrypt access token
    caseManagement -> caseManagementDB: Store encrypted access token
end

user -> caseManagement: Export artifact requirement
caseManagement -> Jira: Export requirements (with access token) to Ticket
Jira -> caseManagement: Ticket updated
caseManagement -> user: Requirements exported

@enduml
